services:
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   volumes:
  #     - /app/node_modules
  #     - ./client:/app
  #   environment:
  #     - WDS_SOCKET_PORT=0

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongo1
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: nverma
      MONGO_INITDB_ROOT_PASSWORD: teret
    volumes:
      - ./db_data:/data/db/

  # nginx:
  #   restart: unless-stopped
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./nginx
  #   depends_on:
  #     - api
  #     - client
  #   ports:
  #     - "3050:80"
volumes:
  mongodb_data: