name: Docker Image CI

on:
  push:
    branches: [ "nutan/groomies" ]
  workflow_dispatch:
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "naveenverma088" --password-stdin
    
      
      - name: Build and push API image
        run: |
          cd server
          docker build . --file Dockerfile --tag naveenverma088/bookmakers_dockerized-api:latest
          docker push naveenverma088/nutan-groomies_dockerized-api:latest
    
